# Generated by Django 5.2 on 2025-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0002_affiliatewallet_affiliatetransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliatewithdrawalrequest",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="affiliatewithdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("processing", "Processing"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
